try to create with mkchroot

diff --git a/bin/mkiso.in b/bin/mkiso.in
--- a/bin/mkiso.in
+++ b/bin/mkiso.in
@@ -125,12 +125,42 @@ _pacman ()
     local ret
     mkdir -p "${work_dir}/${IMAGE_FOLDER}/var/lib/pacman"
     if [ "${QUIET}" = "y" ]; then
+	# eventually replace it with mkchroot to get better mout handling
         setarch ${ARCH} basestrap -GMcd "${work_dir}/${IMAGE_FOLDER}" --config "$PACCONFIG" $* &> /dev/null
+        # make the chroot compatible to use chroot-run
         echo "$version" > "${work_dir}/${IMAGE_FOLDER}/.manjaro-tools"
         ret=$?
     else
+	# eventually replace it with mkchroot to get better mout handling
         setarch ${ARCH} basestrap -GMcd "${work_dir}/${IMAGE_FOLDER}" --config "$PACCONFIG" $*
+        # make the chroot compatible to use chroot-run
         echo "$version" > "${work_dir}/${IMAGE_FOLDER}/.manjaro-tools"
+        ret=$?
+    fi
+
+    if [ -e "${work_dir}/root-image/etc/locale.gen" ]; then
+        cp ${work_dir}/root-image/etc/locale.gen ${work_dir}/root-image/etc/locale.gen.bak
+    fi
+
+    # Cleanup
+    find "${work_dir}" -name *.pacnew -name *.pacsave -name *.pacorig -delete
+
+    if [ $ret -ne 0 ]; then
+        exit 1
+    fi
+}
+
+_mkchroot ()
+{
+    local ret
+    #mkdir -p "${work_dir}/${IMAGE_FOLDER}/var/lib/pacman"
+    if [ "${QUIET}" = "y" ]; then
+        setarch "${ARCH}" \
+	    mkchroot -C "${PACCONFIG}" "${work_dir}/${IMAGE_FOLDER}" "$@" &> /dev/null
+        ret=$?
+    else
+        setarch "${ARCH}" \
+	    mkchroot -C "${PACCONFIG}" "${work_dir}/${IMAGE_FOLDER}" "$@"
         ret=$?
     fi
 
@@ -153,7 +183,7 @@ command_create () {
 
     if [ ! -z "${PKGLIST}" ]; then
         msg2 "Installing packages to '${work_dir}/${IMAGE_FOLDER}/'"
-        _pacman "${PKGLIST}"
+        _mkchroot "${PKGLIST}"
 
         msg2 "Cleaning up what we can"
         if [ -d "${work_dir}/${IMAGE_FOLDER}/boot/" ]; then
@@ -164,7 +194,7 @@ command_create () {
         if [ ${CREATE_DEFAULT} == "y" ]; then
             if [ -d "${work_dir}/${IMAGE_FOLDER}/home/" ]; then
                 msg2 "Creating default home directory"
-                install -d -o1000 -g100 -m0755 "${work_dir}/${IMAGE_FOLDER}/home/manjaro"
+                install -d -o1000 -g100 -m0755 "${work_dir}/${IMAGE_FOLDER}/home/${username}"
             fi
         fi
 
