first merging

diff --git a/manjaro-chroot.in b/manjaro-chroot.in
--- a/manjaro-chroot.in
+++ b/manjaro-chroot.in
@@ -2,7 +2,7 @@
 
 shopt -s extglob
 
-# generated from util-linux source: libmount/src/utils.c
+# # generated from util-linux source: libmount/src/utils.c
 # declare -A pseudofs_types=([anon_inodefs]=1
 #                            [autofs]=1
 #                            [bdev]=1
@@ -46,25 +46,25 @@ shopt -s extglob
 #                        [reiserfs]=1
 #                        [vfat]=1
 #                        [xfs]=1)
-#
+
 # out() { printf "$1 $2\n" "${@:3}"; }
 # error() { out "==> ERROR:" "$@"; } >&2
 # msg() { out "==>" "$@"; }
 # msg2() { out "  ->" "$@";}
 # die() { error "$@"; exit 1; }
-#
+
 # ignore_error() {
 #   "$@" 2>/dev/null
 #   return 0
 # }
-#
+
 # in_array() {
 #   local i
 #   for i in "${@:2}"; do
 #     [[ $1 = "$i" ]] && return
 #   done
 # }
-#
+
 # track_mount() {
 #   if [[ -z $CHROOT_ACTIVE_MOUNTS ]]; then
 #     CHROOT_ACTIVE_MOUNTS=()
@@ -97,7 +97,7 @@ shopt -s extglob
 # chroot_umount() {
 #   umount "${CHROOT_ACTIVE_MOUNTS[@]}"
 # }
-#
+
 # valid_number_of_base() {
 #   local base=$1 len=${#2} i=
 #
@@ -160,7 +160,7 @@ shopt -s extglob
 #     error 'Failed to resolve device mapper name for: %s' "$1"
 #   fi
 # }
-#
+
 # fstype_is_pseudofs() {
 #   (( pseudofs_types["$1"] ))
 # }
@@ -172,58 +172,13 @@ shopt -s extglob
 
 source @libdir@/functions.sh
 
-write_source() {
-  local src=$1 spec= label= uuid= comment=()
-
-  label=$(lsblk -rno LABEL "$1" 2>/dev/null)
-  uuid=$(lsblk -rno UUID "$1" 2>/dev/null)
-
-  # bind mounts do not have a UUID!
-
-  case $bytag in
-    '')
-      [[ $uuid ]] && comment=("UUID=$uuid")
-      [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
-      ;;
-    LABEL)
-      spec=$label
-      [[ $uuid ]] && comment=("$src" "UUID=$uuid")
-      ;;
-    UUID)
-      spec=$uuid
-      comment=("$src")
-      [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
-      ;;
-    *)
-      [[ $uuid ]] && comment=("$1" "UUID=$uuid")
-      [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
-      [[ $bytag ]] && spec=$(lsblk -rno "$bytag" "$1" 2>/dev/null)
-      ;;
-  esac
-
-  [[ $comment ]] && printf '# %s\n' "${comment[*]}"
-
-  if [[ $spec ]]; then
-    printf '%-20s' "$bytag=$(mangle "$spec")"
-  else
-    printf '%-20s' "$(mangle "$src")"
-  fi
-}
-
 usage() {
   cat <<EOF
-usage: ${0##*/} [options] root
-
-  Options:
-    -L             Use labels for source identifiers (shortcut for -t LABEL)
-    -p             Avoid printing pseudofs mounts
-    -t TAG         Use TAG for source identifiers
-    -U             Use UUIDs for source identifiers (shortcut for -t UUID)
+usage: ${0##*/} chroot-dir [command]
 
     -h             Print this help message
 
-genfstab generates output suitable for addition to an fstab file based on the
-devices mounted under the mountpoint specified by the given root.
+If 'command' is unspecified, ${0##*/} will launch /bin/sh.
 
 EOF
 }
@@ -233,128 +188,13 @@ if [[ -z $1 || $1 = @(-h|--help) ]]; then
   exit $(( $# ? 0 : 1 ))
 fi
 
-while getopts ':Lpt:U' flag; do
-  case $flag in
-    L)
-      bytag=LABEL
-      ;;
-    U)
-      bytag=UUID
-      ;;
-    p)
-      nopseudofs=1
-      ;;
-    t)
-      bytag=${OPTARG^^}
-      ;;
-    :)
-      die '%s: option requires an argument -- '\''%s'\' "${0##*/}" "$OPTARG"
-      ;;
-    ?)
-      die '%s: invalid option -- '\''%s'\' "${0##*/}" "$OPTARG"
-      ;;
-  esac
-done
-shift $(( OPTIND - 1 ))
+(( EUID == 0 )) || die 'This script must be run with root privileges'
+chrootdir=$1
+shift
 
-(( $# )) || die "No root directory specified"
-root=$1; shift
+[[ -d $chrootdir ]] || die "Can't create chroot on non-directory %s" "$chrootdir"
 
-if ! mountpoint -q "$root"; then
-  die "$root is not a mountpoint"
-fi
+api_fs_mount "$chrootdir" || die "failed to setup API filesystems in chroot %s" "$chrootdir"
+track_mount /etc/resolv.conf "$chrootdir/etc/resolv.conf" --bind
 
-# handle block devices
-findmnt -Recvruno SOURCE,TARGET,FSTYPE,OPTIONS,FSROOT "$root" |
-    while read -r src target fstype opts fsroot; do
-  if (( nopseudofs )) && fstype_is_pseudofs "$fstype"; then
-    continue
-  fi
-
-  # default 5th and 6th columns
-  dump=0 pass=2
-
-  src=$(unmangle "$src")
-  target=$(unmangle "$target")
-  target=${target#$root}
-
-  if (( !foundroot )) && findmnt "$src" "$root" >/dev/null; then
-    # this is root. we can't possibly have more than one...
-    pass=1 foundroot=1
-  fi
-
-  # if there's no fsck tool available, then only pass=0 makes sense.
-  if ! fstype_has_fsck "$fstype"; then
-    pass=0
-  fi
-
-  if [[ $fsroot != / ]]; then
-    if [[ $fstype = btrfs ]]; then
-      opts+=,subvol=${fsroot#/}
-    else
-      # it's a bind mount
-      src=$(findmnt -funcevo TARGET "$src")$fsroot
-      if [[ $src -ef $target ]]; then
-        # hrmm, this is weird. we're probably looking at a file or directory
-        # that was bound into a chroot from the host machine. Ignore it,
-        # because this won't actually be a valid mount. Worst case, the user
-        # just re-adds it.
-        continue
-      fi
-      fstype=none
-      opts+=,bind
-      pass=0
-    fi
-  fi
-
-  # filesystem quirks
-  case $fstype in
-    fuseblk)
-      # well-behaved FUSE filesystems will report themselves as fuse.$fstype.
-      # this is probably NTFS-3g, but let's just make sure.
-      if ! newtype=$(lsblk -no FSTYPE "$src") || [[ -z $newtype ]]; then
-        # avoid blanking out fstype, leading to an invalid fstab
-        error 'Failed to derive real filesystem type for FUSE device on %s' "$target"
-      else
-        fstype=$newtype
-      fi
-      ;;
-  esac
-
-  # write one line
-  write_source "$src"
-  printf '\t%-10s' "/$(mangle "${target#/}")" "$fstype" "$opts"
-  printf '\t%s %s' "$dump" "$pass"
-  printf '\n\n'
-done
-
-# handle swaps devices
-{
-  # ignore header
-  read
-
-  while read -r device type _ _ prio; do
-    options=defaults
-    if [[ $prio != -1 ]]; then
-      options+=,pri=$prio
-    fi
-
-    # skip files marked deleted by the kernel
-    [[ $device = *'\040(deleted)' ]] && continue
-
-    if [[ $type = file ]]; then
-      printf '%-20s' "$device"
-    elif [[ $device = /dev/dm-+([0-9]) ]]; then
-      # device mapper doesn't allow characters we need to worry
-      # about being mangled, and it does the escaping of dashes
-      # for us in sysfs.
-      write_source "$(dm_name_for_devnode "$device")"
-    else
-      write_source "$(unmangle "$device")"
-    fi
-
-    printf '\t%-10s\t%-10s\t%-10s\t0 0\n\n' 'none' 'swap' "$options"
-  done
-} </proc/swaps
-
-# vim: et ts=2 sw=2 ft=sh:
+SHELL=/bin/sh chroot "$chrootdir" "$@"
